### ISSUE TITLE
Use trie for iri to curie conversion

### ISSUE THREAD

**Issue by kshefchek** [prefixcommons/prefixcommons-py#5]
Similar to https://github.com/RDFLib/rdflib/pull/649/files
and
https://github.com/prefixcommons/curie-util

**Comment by cthoyt** [comment]
I've got an implementation based on [`curies`](https://github.com/cthoyt/curies), but waiting on #21 and #22 to get merged to send a PR for this to reduce diff. If you already want to see the code (with a big diff) you can check https://github.com/prefixcommons/prefixcommons-py/compare/master...cthoyt:prefixcommons-py:externalize-impl
